// Generated by gencpp from file custom_msgs/PnP.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_PNP_H
#define CUSTOM_MSGS_MESSAGE_PNP_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace custom_msgs
{
template <class ContainerAllocator>
struct PnP_
{
  typedef PnP_<ContainerAllocator> Type;

  PnP_()
    : header()
    , data()  {
      data.assign(0.0);
  }
  PnP_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , data()  {
  (void)_alloc;
      data.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef boost::array<float, 4>  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::custom_msgs::PnP_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::PnP_<ContainerAllocator> const> ConstPtr;

}; // struct PnP_

typedef ::custom_msgs::PnP_<std::allocator<void> > PnP;

typedef boost::shared_ptr< ::custom_msgs::PnP > PnPPtr;
typedef boost::shared_ptr< ::custom_msgs::PnP const> PnPConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::PnP_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::PnP_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_msgs::PnP_<ContainerAllocator1> & lhs, const ::custom_msgs::PnP_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_msgs::PnP_<ContainerAllocator1> & lhs, const ::custom_msgs::PnP_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::PnP_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::PnP_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::PnP_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::PnP_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::PnP_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::PnP_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::PnP_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dd55cd564b165fcfd9fb263801895897";
  }

  static const char* value(const ::custom_msgs::PnP_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdd55cd564b165fcfULL;
  static const uint64_t static_value2 = 0xd9fb263801895897ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::PnP_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/PnP";
  }

  static const char* value(const ::custom_msgs::PnP_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::PnP_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"float32[4] data\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::custom_msgs::PnP_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::PnP_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PnP_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::PnP_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::PnP_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_PNP_H
