arm_position_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - bob_joint1
      - bob_joint2
      - bob_joint3
      - bob_joint4
      - bob_joint5
      - bob_joint6
      - bob_joint7
    gains:
      bob_joint1:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      bob_joint2:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      bob_joint3:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      bob_joint4:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      bob_joint5:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      bob_joint6:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      bob_joint7:
        p: 100
        d: 1
        i: 1
        i_clamp: 1

hand_controller:
  type: effort_controllers/GripperActionController
  joint: bob_finger_joint1
    # - bob_finger_joint2